### ISSUE TITLE
convert back to DateTime

### ISSUE THREAD

**Issue by Static-1248** [ssk-flutter/date_only#2]
Wondering why cant it convert back to datetime

**Comment by deviankim** [comment]
Thank you for your feedback on the 'date_only' package. I appreciate you bringing this issue to my attention. Based on your input, I plan to add a feature that allows converting back to a 'datetime' object from a 'date_only' instance. This should enhance the functionality and versatility of the package. I'll keep you updated on the progress and let you know once it's implemented.

Thank you again for helping to improve the package!

**Comment by deviankim** [comment]
This issue has been resolved in version 0.0.5. Please update to the latest version to access the new features and fixes.
